#!/usr/bin/env python3
"""Rasterise a monospace TTF into an 8x16 bitmap font table for the kernel.

The kernel has no font rasteriser and no allocator, so glyphs are baked into
.rodata as one byte per row. Regenerate with:

    python3 tools/genfont.py > kernel/src/font.rs

Source face: DejaVu Sans Mono (Bitstream Vera licence, permissive).
"""
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
FIRST, LAST = 0x20, 0x7E
PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

font = ImageFont.truetype(PATH, 14)
rows = []
for cp in range(FIRST, LAST + 1):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -1), chr(cp), font=font, fill=255)
    px = img.load()
    glyph = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if px[x, y] > 110:
                bits |= 1 << (7 - x)
        glyph.append(bits)
    rows.append((cp, glyph))

print("//! 8x16 bitmap font, generated by tools/genfont.py from DejaVu Sans Mono")
print("//! (Bitstream Vera licence). Do not edit by hand; regenerate instead.")
print("//!")
print("//! One byte per scanline, most significant bit leftmost.")
print()
print(f"pub const GLYPH_W: usize = {W};")
print(f"pub const GLYPH_H: usize = {H};")
print(f"pub const FIRST_CHAR: u8 = 0x{FIRST:02X};")
print(f"pub const LAST_CHAR: u8 = 0x{LAST:02X};")
print()
print(f"pub static FONT: [[u8; GLYPH_H]; {len(rows)}] = [")
for cp, glyph in rows:
    ch = chr(cp).replace("\\", "\\\\").replace("'", "\\'")
    body = ", ".join(f"0x{b:02X}" for b in glyph)
    print(f"    [{body}], // {cp:#04x} '{ch}'")
print("];")
print()
print("""/// Glyph rows for `c`, falling back to a question mark outside the range.
#[inline]
pub fn glyph(c: u8) -> &'static [u8; GLYPH_H] {
    if (FIRST_CHAR..=LAST_CHAR).contains(&c) {
        &FONT[(c - FIRST_CHAR) as usize]
    } else {
        &FONT[(b'?' - FIRST_CHAR) as usize]
    }
}""")
